version: '3.7'

services:
  app: 
    image: manik1235/story_time:latest
    ports:
      - '35001:35001'
    command: ["rails", "s", "-p", "35001", "-b", "0.0.0.0"]
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 3
    environment:
      RAILS_ENV: production

  cmd:
    image: manik1235/story_time:latest
    deploy:
      replicas: 0
