require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/axes", type: :request do
  # Axis. As you add validations to Axis, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
      map_id: FactoryBot.create(:map).id
    }
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        {
          degrees: 190
        }
      end

      it "updates the requested axis" do
        axis = Axis.create! valid_attributes
        patch axis_url(axis), params: { axis: new_attributes }
        axis.reload
        expect(axis.degrees).to eql(190)
      end
    end
  end
end
