 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/hexes", type: :request do
  # Hex. As you add validations to Hex, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Hex.create! valid_attributes
      get hexes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      hex = Hex.create! valid_attributes
      get hex_url(hex)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_hex_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      hex = Hex.create! valid_attributes
      get edit_hex_url(hex)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Hex" do
        expect {
          post hexes_url, params: { hex: valid_attributes }
        }.to change(Hex, :count).by(1)
      end

      it "redirects to the created hex" do
        post hexes_url, params: { hex: valid_attributes }
        expect(response).to redirect_to(hex_url(Hex.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Hex" do
        expect {
          post hexes_url, params: { hex: invalid_attributes }
        }.to change(Hex, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post hexes_url, params: { hex: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested hex" do
        hex = Hex.create! valid_attributes
        patch hex_url(hex), params: { hex: new_attributes }
        hex.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the hex" do
        hex = Hex.create! valid_attributes
        patch hex_url(hex), params: { hex: new_attributes }
        hex.reload
        expect(response).to redirect_to(hex_url(hex))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        hex = Hex.create! valid_attributes
        patch hex_url(hex), params: { hex: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested hex" do
      hex = Hex.create! valid_attributes
      expect {
        delete hex_url(hex)
      }.to change(Hex, :count).by(-1)
    end

    it "redirects to the hexes list" do
      hex = Hex.create! valid_attributes
      delete hex_url(hex)
      expect(response).to redirect_to(hexes_url)
    end
  end
end
